//list of words to guess.
exports.newWord = {
    wordList: ['HOUSE STARK', 'SANSA', 'WILDLINGS', 'THE UNSULLIED', 'I DRINK AND I KNOW THINGS', 'KHAL DROGO', 'WINTER IS COMING', 'THE NIGHT KING', 'KING IN THE NORTH', 'DIREWOLF', 'THE RED KEEP', 'LORD LITTLEFINGER']
};
